# Generated by Django 3.1.4 on 2021-01-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_skill_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='descr',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
