# Generated by Django 3.1.4 on 2021-02-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_project_softskill'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hasLink',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='stack',
            field=models.CharField(default=True, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
