# Generated by Django 3.1.4 on 2021-05-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_auto_20210501_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='level',
        ),
    ]
