# Generated by Django 3.1.4 on 2021-09-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cv', '0010_workexperience_time_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='stack',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr_en',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='skill',
            name='descr',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='descr_en',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='descr',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='descr_en',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='descr',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='descr_en',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='time_en',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
