# Generated by Django 3.1.4 on 2021-09-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cv', '0011_auto_20210920_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='descr',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='descr_en',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='stack',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='descr',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='softskill',
            name='descr_en',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='descr',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='descr_en',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='stack',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
