# Generated by Django 3.1.4 on 2021-09-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cv', '0012_auto_20210920_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='type',
            field=models.CharField(
                choices=[('backend', 'backend'), ('frontend', 'frontend'), ('ds', 'ds'), ('General', 'General')],
                max_length=100),
        ),
    ]
